plugins {
    id 'com.android.application'
}

android {
    namespace 'com.stepan.skyboundrunner'
    compileSdk 35

    defaultConfig {
        applicationId 'com.stepan.skyboundrunner'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '0.1.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
